import {
  mdiAccessPointNetwork, mdiAirConditioner, mdiAirHumidifier, mdiAlarmPanel, mdiAmazonAlexa, mdiAmplifier, mdiBed, mdiBedKing, mdiCamera, mdiCctv, mdiCeilingLight, mdiCoachLamp, mdiCoffeeMaker, mdiConsoleNetwork, mdiDeskLamp, mdiDesktopClassic, mdiDoorbell, mdiDoorbellVideo, mdiFloorLamp, mdiFridge, mdiGarage, mdiGauge, mdiHome, mdiHomeVariant, mdiKettle, mdiLamp, mdiLamps, mdiLan, mdiLaptop, mdiLavaLamp, mdiLedOn, mdiLedStrip, mdiLightbulb, mdiLightbulbCfl, mdiLightbulbGroup, mdiLightSwitch, mdiLock, mdiLockSmart, mdiMicrowave, mdiMirror, mdiMotionSensor, mdiMowerBag, mdiNas, mdiOutdoorLamp, mdiPipe, mdiPipeLeak, mdiPowerPlug, mdiPowerSocketAu, mdiPowerSocketDe, mdiPowerSocketEu, mdiPowerSocketFr, mdiPowerSocketJp, mdiPowerSocketUk, mdiPowerSocketUs, mdiPrinter, mdiProjector, mdiRecordPlayer, mdiRemote, mdiRouterNetwork, mdiSecurityNetwork, mdiServerNetwork, mdiShower, mdiSpeaker, mdiTelevision, mdiThermometer, mdiThermostat, mdiToaster, mdiToilet, mdiTumbleDryer, mdiVanityLight, mdiWan, mdiWashingMachine, mdiWindowShutter
} from "@mdi/js";

export const homeAutomationIcons: { [key: string]: string } = {
  "Air Conditioner": mdiAirConditioner,
  "Air Humidifier": mdiAirHumidifier,
  "Alarm Panel": mdiAlarmPanel,
  "Amplifier": mdiAmplifier,
  "Amazon Alexa": mdiAmazonAlexa,
  "Bed": mdiBed,
  "Bed King": mdiBedKing,
  "Camera": mdiCamera,
  "Camera 2": mdiCctv,
  "Ceiling Lamp": mdiCeilingLight,
  "Coach Lamp": mdiCoachLamp,
  "Coffee Maker": mdiCoffeeMaker,
  "Desk Lamp": mdiDeskLamp,
  "Desktop": mdiDesktopClassic,
  "Doorbell": mdiDoorbell,
  "Doorbell (Video)": mdiDoorbellVideo,
  "Floor Lamp": mdiFloorLamp,
  "Fridge": mdiFridge,
  "Garage": mdiGarage,
  "Gauge": mdiGauge,
  "Home": mdiHome,
  "Home 2": mdiHomeVariant,
  "Kettle": mdiKettle,
  "Lamp": mdiLamp,
  "Lamps": mdiLamps,
  "Laptop": mdiLaptop,
  "Lava Lamp": mdiLavaLamp,
  "LED": mdiLedOn,
  "LED Strip": mdiLedStrip,
  "Light Switch": mdiLightSwitch,
  "Lightbulb": mdiLightbulb,
  "Lightbulb 2": mdiLightbulbCfl,
  "Lightbulbs": mdiLightbulbGroup,
  "Lock": mdiLock,
  "Lock Smart": mdiLockSmart,
  "Microwave": mdiMicrowave,
  "Mirror": mdiMirror,
  "Motion Sensor": mdiMotionSensor,
  "Mower": mdiMowerBag,
  "Outdoor Lamp": mdiOutdoorLamp,
  "Pipe": mdiPipe,
  "Pipe Leak Detector": mdiPipeLeak,
  "Power Plug": mdiPowerPlug,
  "Power Socket AU": mdiPowerSocketAu,
  "Power Socket DE": mdiPowerSocketDe,
  "Power Socket EU": mdiPowerSocketEu,
  "Power Socket FR": mdiPowerSocketFr,
  "Power Socket JP": mdiPowerSocketJp,
  "Power Socket UK": mdiPowerSocketUk,
  "Power Socket US": mdiPowerSocketUs,
  "Printer": mdiPrinter,
  "Projector": mdiProjector,
  "Record Player": mdiRecordPlayer,
  "Remote": mdiRemote,
  "Shower": mdiShower,
  "Speaker": mdiSpeaker,
  "Television": mdiTelevision,
  "Thermometer": mdiThermometer,
  "Thermostat": mdiThermostat,
  "Toaster": mdiToaster,
  "Toilet": mdiToilet,
  "Tumble Dryer": mdiTumbleDryer,
  "Vanity Lamp": mdiVanityLight,
  "Washing Machine": mdiWashingMachine,
  "Window Shutter": mdiWindowShutter,
}

export const networkIcons: { [key: string]: string } = {
  "Access Point": mdiAccessPointNetwork,
  "Console": mdiConsoleNetwork,
  "LAN": mdiLan,
  "NAS": mdiNas,
  "Router": mdiRouterNetwork,
  "Security": mdiSecurityNetwork,
  "Server": mdiServerNetwork,
  "WAN": mdiWan,
}
