mutation Mutation($stackID: String!, $satellite: GQLSatelliteInput!) {
    upsertSatellite(stackID: $stackID, satellite: $satellite) {
        id
        displayName
        leases {
            id
            revokedDate
            userID
        }
    }
}