name: Build and Push

on:
  workflow_dispatch:
    on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Sources
      - name: Checkout Sources
        uses: actions/checkout@v2

      # Login to Nexus
      - uses: azure/docker-login@v1
        with:
          login-server: images.conceptive.io
          username: ${{ secrets.nexus_user }}
          password: ${{ secrets.nexus_password }}

      # Build Docker Image
      - name: Build
        run: docker build -t images.conceptive.io/homestack.frontend:latest .

      # Push Docker Image
      - name: Push
        run: docker push images.conceptive.io/homestack.frontend:latest
