name: Compile / onTagged

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup / Checkout
        uses: actions/checkout@v2

      - name: Setup / Environment Variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup / Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: images.conceptive.io
          username: ${{ secrets.nexus_user }}
          password: ${{ secrets.nexus_password }}

      - name: Compile / Build
        run: docker build -t images.conceptive.io/homestack.frontend:latest -t images.conceptive.io/homestack.frontend:${{ env.RELEASE_VERSION }} .

      - name: Deploy / Docker
        run: |
          docker push images.conceptive.io/homestack.frontend:latest
          docker push images.conceptive.io/homestack.frontend:${{ env.RELEASE_VERSION }}
